"""
FastAPI High-Performance Backend API Package.
Exports FastAPI application instance and schemas.
"""

from .main import app, create_app
from .schemas import (
    HealthResponse,
    ErrorResponse,
    DatasetSummaryResponse,
    CorrelationResponse,
    DistributionsResponse,
    DataSampleResponse,
    DataUploadResponse,
    ClusteringRequest,
    ClusteringResponse,
    ProjectionsResponse,
    ClusterProfilesResponse,
    SilhouetteSamplesResponse,
    ElbowResponse,
    AutoresearchStartRequest,
    AutoresearchStartResponse,
    AutoresearchStatusResponse,
    LeaderboardResponse,
    AutoresearchAblationSummary,
    LiteratureResponse,
    BenchmarkMatrixResponse,
    AblationMatrixResponse,
    TableExportRequest,
    TableExportResponse,
    SingleInferenceRequest,
    SingleInferenceResponse,
    BatchInferenceRequest,
    BatchInferenceResponse,
)

__all__ = [
    "app",
    "create_app",
    "HealthResponse",
    "ErrorResponse",
    "DatasetSummaryResponse",
    "CorrelationResponse",
    "DistributionsResponse",
    "DataSampleResponse",
    "DataUploadResponse",
    "ClusteringRequest",
    "ClusteringResponse",
    "ProjectionsResponse",
    "ClusterProfilesResponse",
    "SilhouetteSamplesResponse",
    "ElbowResponse",
    "AutoresearchStartRequest",
    "AutoresearchStartResponse",
    "AutoresearchStatusResponse",
    "LeaderboardResponse",
    "AutoresearchAblationSummary",
    "LiteratureResponse",
    "BenchmarkMatrixResponse",
    "AblationMatrixResponse",
    "TableExportRequest",
    "TableExportResponse",
    "SingleInferenceRequest",
    "SingleInferenceResponse",
    "BatchInferenceRequest",
    "BatchInferenceResponse",
]
