import {
  DatasetHealth,
  CrispDmPhase,
  FeatureSummary,
  CorrelationMatrix,
  ClusteringModelSummary,
  ClusterPersona,
  ClusterPoint2D,
  ClusterPoint3D,
  SilhouetteSample,
  ElbowPoint,
  AutoresearchStep,
  AutoresearchLeaderboardItem,
  BenchmarkRow,
  AblationEntry,
  LiteraturePaper,
  CustomerVector,
  InferenceResponse
} from '../types/api';

export const mockDatasetHealth: DatasetHealth = {
  totalRows: 8950,
  totalFeatures: 18,
  missingValuesCount: 314,
  missingValuesRate: 0.0351, // 3.5%
  outliersDetected: 376,
  outlierRate: 0.042, // 4.2%
  memoryUsageMb: 1.23,
  hopkinsStatistic: 0.8842, // High clustering tendency (> 0.7)
  duplicateRows: 0,
  lastUpdated: '2026-08-28T08:00:00Z',
};

export const mockCrispDmPhases: CrispDmPhase[] = [
  {
    phaseId: 1,
    code: 'BU',
    name: 'Business Understanding',
    status: 'completed',
    badge: 'Strategic Alignment',
    description: 'Deconstruct customer financial behaviors to design tailored credit limits, revolving APR incentives, and targeted reward programs.',
    kpis: [
      { label: 'Target Segments', value: '4 Archetypes' },
      { label: 'Primary KPI', value: 'Silhouette > 0.55' },
      { label: 'Business Focus', value: 'Credit Risk & Upsell' },
    ],
    details: [
      'Segment customers by liquidity seeking vs transacting behaviors.',
      'Differentiate high-risk revolving balances from safe transactors.',
      'Establish multi-metric evaluation criteria (Silhouette, Davies-Bouldin, Stability).',
    ],
    actionRoute: '/overview',
  },
  {
    phaseId: 2,
    code: 'DU',
    name: 'Data Understanding',
    status: 'completed',
    badge: 'EDA & Quality Audit',
    description: 'Exploratory data analysis across 8,950 accounts and 17 numeric behavioral attributes. Quantify skewness, kurtosis, and correlation.',
    kpis: [
      { label: 'Total Records', value: '8,950 accounts' },
      { label: 'Missing Fields', value: 'MIN_PAY (3.5%), LIMIT (1)' },
      { label: 'Hopkins Statistic', value: '0.884 (Clustered)' },
    ],
    details: [
      'Identified extreme positive skewness (> 3.5) in PURCHASES and CASH_ADVANCE.',
      'Discovered collinearity between PURCHASES and ONEOFF_PURCHASES (r = 0.91).',
      'Assessed spatial clustering tendency via Hopkins statistic (0.884).',
    ],
    actionRoute: '/overview',
  },
  {
    phaseId: 3,
    code: 'DP',
    name: 'Data Preparation',
    status: 'completed',
    badge: 'Pipeline Ready',
    description: 'Automated data cleaning, robust imputation, Yeo-Johnson power transformations, and multi-dimensional projection embeddings.',
    kpis: [
      { label: 'Imputation', value: 'Median + KNN Imputer' },
      { label: 'Scaling', value: 'PowerTransformer (Yeo-Johnson)' },
      { label: 'Projections', value: 'PCA (95% var) / UMAP' },
    ],
    details: [
      'Median imputation for missing MINIMUM_PAYMENTS and CREDIT_LIMIT.',
      'Winsorization at 1st/99th percentiles to curb non-informative outliers.',
      'Yeo-Johnson power transformation to normalize heavy-tailed distributions.',
    ],
    actionRoute: '/overview',
  },
  {
    phaseId: 4,
    code: 'MOD',
    name: 'Modeling',
    status: 'completed',
    badge: '6 Models / 4 Paradigms',
    description: 'Rigorous experimentation spanning Partitioning (K-Means, K-Medoids), Density (DBSCAN, HDBSCAN), Hierarchical, and Probabilistic (GMM).',
    kpis: [
      { label: 'Algorithms', value: '6 Benchmark Models' },
      { label: 'Optimal k', value: 'k = 4 (Kneedle)' },
      { label: 'Search Space', value: '480 Pipeline Combos' },
    ],
    details: [
      'K-Means++ with Lloyd iterations and Kneedle elbow analysis.',
      'HDBSCAN density clustering with soft noise reassignment.',
      'Agglomerative clustering with Ward linkage variance minimization.',
    ],
    actionRoute: '/clusters',
  },
  {
    phaseId: 5,
    code: 'EVAL',
    name: 'Evaluation',
    status: 'completed',
    badge: 'Multi-Metric Rigor',
    description: 'Validation against internal metrics (Silhouette, Davies-Bouldin, Calinski-Harabasz) and 100-fold bootstrap stability tests.',
    kpis: [
      { label: 'Peak Silhouette', value: '0.584 ± 0.009' },
      { label: 'Davies-Bouldin', value: '0.812 (Lowest)' },
      { label: 'Bootstrap ARI', value: '0.982 (Stable)' },
    ],
    details: [
      'Comparative evaluation across all paradigms on identical 10-fold CV.',
      'Ablation study proving +0.142 Silhouette gain from Autoresearch optimization.',
      'Validated cluster profiles against financial domain hypotheses.',
    ],
    actionRoute: '/benchmarks',
  },
  {
    phaseId: 6,
    code: 'DEP',
    name: 'Deployment',
    status: 'completed',
    badge: 'Production Serving',
    description: 'Sub-millisecond REST scoring endpoint with real-time customer profiler playground, confidence scoring, and automated BibTeX citation export.',
    kpis: [
      { label: 'Inference Latency', value: '< 2.5 ms' },
      { label: 'API Protocols', value: 'REST + SSE Stream' },
      { label: 'Serving Framework', value: 'FastAPI + Next.js' },
    ],
    details: [
      'Interactive customer archetype playground with instant segment attribution.',
      'Batch CSV scoring dropzone for asynchronous bulk inferences.',
      'Automated LaTeX and BibTeX paper-ready synthesis generation.',
    ],
    actionRoute: '/playground',
  },
];

export const mockFeatureSummaries: FeatureSummary[] = [
  {
    name: 'BALANCE',
    dataType: 'float64',
    mean: 1564.47,
    std: 2081.53,
    min: 0.0,
    median: 873.39,
    max: 19043.14,
    skewness: 2.39,
    kurtosis: 7.67,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Monthly average account balance maintained by customer.',
    histogramBins: [
      { bin: '$0-$1k', count: 4720 },
      { bin: '$1k-$3k', count: 2410 },
      { bin: '$3k-$5k', count: 1080 },
      { bin: '$5k-$10k', count: 580 },
      { bin: '>$10k', count: 160 },
    ],
  },
  {
    name: 'BALANCE_FREQUENCY',
    dataType: 'float64',
    mean: 0.88,
    std: 0.24,
    min: 0.0,
    median: 1.0,
    max: 1.0,
    skewness: -2.02,
    kurtosis: 3.10,
    missingCount: 0,
    missingRate: 0.0,
    description: 'How frequently the balance is updated (1 = frequently updated).',
    histogramBins: [
      { bin: '0.0-0.2', count: 420 },
      { bin: '0.2-0.5', count: 560 },
      { bin: '0.5-0.8', count: 910 },
      { bin: '0.8-0.99', count: 1120 },
      { bin: '1.0', count: 5940 },
    ],
  },
  {
    name: 'PURCHASES',
    dataType: 'float64',
    mean: 1003.20,
    std: 2136.63,
    min: 0.0,
    median: 361.28,
    max: 49039.57,
    skewness: 7.42,
    kurtosis: 111.38,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Total dollar amount of purchases made on the account.',
    histogramBins: [
      { bin: '$0-$500', count: 5210 },
      { bin: '$500-$2k', count: 2490 },
      { bin: '$2k-$5k', count: 920 },
      { bin: '$5k-$10k', count: 240 },
      { bin: '>$10k', count: 90 },
    ],
  },
  {
    name: 'ONEOFF_PURCHASES',
    dataType: 'float64',
    mean: 592.44,
    std: 1659.89,
    min: 0.0,
    median: 38.0,
    max: 40761.25,
    skewness: 10.05,
    kurtosis: 222.11,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Maximum purchase amount done in one-go.',
    histogramBins: [
      { bin: '$0', count: 4400 },
      { bin: '$1-$500', count: 2600 },
      { bin: '$500-$2k', count: 1420 },
      { bin: '$2k-$5k', count: 410 },
      { bin: '>$5k', count: 120 },
    ],
  },
  {
    name: 'INSTALLMENTS_PURCHASES',
    dataType: 'float64',
    mean: 411.06,
    std: 904.34,
    min: 0.0,
    median: 89.0,
    max: 22500.0,
    skewness: 7.29,
    kurtosis: 96.53,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Purchases amount paid in monthly installments.',
    histogramBins: [
      { bin: '$0', count: 3900 },
      { bin: '$1-$500', count: 3310 },
      { bin: '$500-$1.5k', count: 1320 },
      { bin: '$1.5k-$3k', count: 320 },
      { bin: '>$3k', count: 100 },
    ],
  },
  {
    name: 'CASH_ADVANCE',
    dataType: 'float64',
    mean: 978.83,
    std: 2097.16,
    min: 0.0,
    median: 0.0,
    max: 47137.21,
    skewness: 5.16,
    kurtosis: 52.89,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Cash in advance drawn by the customer (ATM/teller).',
    histogramBins: [
      { bin: '$0', count: 4620 },
      { bin: '$1-$1k', count: 2450 },
      { bin: '$1k-$3k', count: 1280 },
      { bin: '$3k-$7k', count: 470 },
      { bin: '>$7k', count: 130 },
    ],
  },
  {
    name: 'PURCHASES_FREQUENCY',
    dataType: 'float64',
    mean: 0.49,
    std: 0.40,
    min: 0.0,
    median: 0.50,
    max: 1.0,
    skewness: 0.06,
    kurtosis: -1.63,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Frequency with which purchases are being made (0 to 1).',
    histogramBins: [
      { bin: '0.0-0.1', count: 2980 },
      { bin: '0.1-0.4', count: 1420 },
      { bin: '0.4-0.7', count: 1530 },
      { bin: '0.7-0.9', count: 1010 },
      { bin: '0.9-1.0', count: 2010 },
    ],
  },
  {
    name: 'CASH_ADVANCE_FREQUENCY',
    dataType: 'float64',
    mean: 0.14,
    std: 0.20,
    min: 0.0,
    median: 0.0,
    max: 1.5,
    skewness: 1.83,
    kurtosis: 3.34,
    missingCount: 0,
    missingRate: 0.0,
    description: 'How frequently the cash in advance is being paid.',
    histogramBins: [
      { bin: '0.0', count: 4620 },
      { bin: '0.01-0.2', count: 2310 },
      { bin: '0.2-0.5', count: 1480 },
      { bin: '0.5-0.8', count: 420 },
      { bin: '>0.8', count: 120 },
    ],
  },
  {
    name: 'CREDIT_LIMIT',
    dataType: 'float64',
    mean: 4494.45,
    std: 3638.82,
    min: 50.0,
    median: 3000.0,
    max: 30000.0,
    skewness: 1.52,
    kurtosis: 2.84,
    missingCount: 1,
    missingRate: 0.0001,
    description: 'Limit of credit card assigned to the user.',
    histogramBins: [
      { bin: '$0-$2k', count: 2850 },
      { bin: '$2k-$5k', count: 3740 },
      { bin: '$5k-$10k', count: 1810 },
      { bin: '$10k-$15k', count: 440 },
      { bin: '>$15k', count: 110 },
    ],
  },
  {
    name: 'PAYMENTS',
    dataType: 'float64',
    mean: 1733.14,
    std: 2895.06,
    min: 0.0,
    median: 856.90,
    max: 50721.50,
    skewness: 5.91,
    kurtosis: 54.77,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Amount of payment done by customer.',
    histogramBins: [
      { bin: '$0-$1k', count: 5010 },
      { bin: '$1k-$3k', count: 2680 },
      { bin: '$3k-$6k', count: 910 },
      { bin: '$6k-$12k', count: 260 },
      { bin: '>$12k', count: 90 },
    ],
  },
  {
    name: 'MINIMUM_PAYMENTS',
    dataType: 'float64',
    mean: 864.21,
    std: 2372.45,
    min: 0.02,
    median: 312.34,
    max: 76406.21,
    skewness: 13.62,
    kurtosis: 283.96,
    missingCount: 313,
    missingRate: 0.035,
    description: 'Minimum amount of payments made by user during period.',
    histogramBins: [
      { bin: '$0-$300', count: 4320 },
      { bin: '$300-$1k', count: 2980 },
      { bin: '$1k-$3k', count: 1050 },
      { bin: '$3k-$7k', count: 220 },
      { bin: '>$7k', count: 67 },
    ],
  },
  {
    name: 'PRC_FULL_PAYMENT',
    dataType: 'float64',
    mean: 0.15,
    std: 0.29,
    min: 0.0,
    median: 0.0,
    max: 1.0,
    skewness: 1.95,
    kurtosis: 2.42,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Percent of full payment paid by user.',
    histogramBins: [
      { bin: '0%', count: 5900 },
      { bin: '1%-20%', count: 1120 },
      { bin: '20%-50%', count: 750 },
      { bin: '50%-99%', count: 590 },
      { bin: '100%', count: 590 },
    ],
  },
  {
    name: 'TENURE',
    dataType: 'int64',
    mean: 11.52,
    std: 1.34,
    min: 6,
    median: 12,
    max: 12,
    skewness: -2.94,
    kurtosis: 7.69,
    missingCount: 0,
    missingRate: 0.0,
    description: 'Tenure of credit card service for user (in months).',
    histogramBins: [
      { bin: '6 mos', count: 204 },
      { bin: '7-8 mos', count: 298 },
      { bin: '9-10 mos', count: 412 },
      { bin: '11 mos', count: 452 },
      { bin: '12 mos', count: 7584 },
    ],
  },
];

export const mockCorrelationMatrix: CorrelationMatrix = {
  features: [
    'BALANCE',
    'PURCHASES',
    'ONEOFF_PURCHASES',
    'INSTALLMENTS',
    'CASH_ADVANCE',
    'PURCH_FREQ',
    'CASH_FREQ',
    'CREDIT_LIMIT',
    'PAYMENTS',
    'PRC_FULL',
  ],
  pearson: [
    [1.0, 0.18, 0.16, 0.13, 0.50, -0.08, 0.45, 0.53, 0.32, -0.32],
    [0.18, 1.0, 0.91, 0.68, -0.05, 0.39, -0.12, 0.36, 0.60, 0.18],
    [0.16, 0.91, 1.0, 0.33, -0.03, 0.26, -0.08, 0.32, 0.57, 0.13],
    [0.13, 0.68, 0.33, 1.0, -0.06, 0.44, -0.13, 0.26, 0.38, 0.18],
    [0.50, -0.05, -0.03, -0.06, 1.0, -0.22, 0.63, 0.30, 0.45, -0.15],
    [-0.08, 0.39, 0.26, 0.44, -0.22, 1.0, -0.26, 0.12, 0.10, 0.31],
    [0.45, -0.12, -0.08, -0.13, 0.63, -0.26, 1.0, 0.13, 0.19, -0.25],
    [0.53, 0.36, 0.32, 0.26, 0.30, 0.12, 0.13, 1.0, 0.42, 0.05],
    [0.32, 0.60, 0.57, 0.38, 0.45, 0.10, 0.19, 0.42, 1.0, 0.11],
    [-0.32, 0.18, 0.13, 0.18, -0.15, 0.31, -0.25, 0.05, 0.11, 1.0],
  ],
  spearman: [
    [1.0, 0.12, 0.10, 0.09, 0.48, -0.11, 0.42, 0.51, 0.30, -0.35],
    [0.12, 1.0, 0.86, 0.74, -0.15, 0.58, -0.18, 0.39, 0.54, 0.24],
    [0.10, 0.86, 1.0, 0.31, -0.11, 0.42, -0.14, 0.34, 0.49, 0.19],
    [0.09, 0.74, 0.31, 1.0, -0.12, 0.61, -0.16, 0.30, 0.41, 0.22],
    [0.48, -0.15, -0.11, -0.12, 1.0, -0.28, 0.79, 0.25, 0.35, -0.20],
    [-0.11, 0.58, 0.42, 0.61, -0.28, 1.0, -0.32, 0.18, 0.16, 0.36],
    [0.42, -0.18, -0.14, -0.16, 0.79, -0.32, 1.0, 0.15, 0.23, -0.28],
    [0.51, 0.39, 0.34, 0.30, 0.25, 0.18, 0.15, 1.0, 0.46, 0.09],
    [0.30, 0.54, 0.49, 0.41, 0.35, 0.16, 0.23, 0.46, 1.0, 0.16],
    [-0.35, 0.24, 0.19, 0.22, -0.20, 0.36, -0.28, 0.09, 0.16, 1.0],
  ],
};

export const mockClusteringModels: ClusteringModelSummary[] = [
  {
    id: 'kmeans_opt',
    name: 'Autoresearch K-Means++ (Best)',
    paradigm: 'Autoresearch',
    k: 4,
    silhouette: 0.5842,
    daviesBouldin: 0.8124,
    calinskiHarabasz: 3921.6,
    stabilityAri: 0.982,
    runtimeMs: 24.2,
    noisePoints: 0,
    description: 'Hill-climbed pipeline with Yeo-Johnson power transforms, PCA feature selection, and k=4 partitioning.',
  },
  {
    id: 'kmeans_base',
    name: 'K-Means (Baseline)',
    paradigm: 'Partitioning',
    k: 4,
    silhouette: 0.4421,
    daviesBouldin: 1.3412,
    calinskiHarabasz: 2842.1,
    stabilityAri: 0.921,
    runtimeMs: 18.4,
    noisePoints: 0,
    description: 'StandardScaler with default k-means++ initialization on raw features.',
  },
  {
    id: 'kmedoids',
    name: 'K-Medoids (FasterPAM)',
    paradigm: 'Partitioning',
    k: 4,
    silhouette: 0.4285,
    daviesBouldin: 1.4102,
    calinskiHarabasz: 2650.4,
    stabilityAri: 0.894,
    runtimeMs: 112.5,
    noisePoints: 0,
    description: 'Medoid-based partitioning using Manhattan distance metrics to resist outlier distortion.',
  },
  {
    id: 'dbscan',
    name: 'DBSCAN',
    paradigm: 'Density',
    k: '3 + Noise',
    silhouette: 0.3812,
    daviesBouldin: 1.6241,
    calinskiHarabasz: 1412.0,
    stabilityAri: 0.812,
    runtimeMs: 42.1,
    noisePoints: 1270,
    description: 'Density contour clustering (eps=0.5, min_samples=5). Isolates sparse noise points.',
  },
  {
    id: 'hdbscan',
    name: 'HDBSCAN',
    paradigm: 'Density',
    k: '4 + Noise',
    silhouette: 0.4951,
    daviesBouldin: 1.0524,
    calinskiHarabasz: 3105.4,
    stabilityAri: 0.941,
    runtimeMs: 88.6,
    noisePoints: 456,
    description: 'Hierarchical density estimates over varying density basins with soft cluster assignment.',
  },
  {
    id: 'agglomerative',
    name: 'Agglomerative (Ward)',
    paradigm: 'Hierarchical',
    k: 4,
    silhouette: 0.4682,
    daviesBouldin: 1.2154,
    calinskiHarabasz: 2980.2,
    stabilityAri: 0.948,
    runtimeMs: 145.0,
    noisePoints: 0,
    description: 'Bottom-up hierarchical clustering minimizing within-cluster variance at each merge.',
  },
  {
    id: 'gmm',
    name: 'Gaussian Mixture Model',
    paradigm: 'Probabilistic',
    k: 4,
    silhouette: 0.4510,
    daviesBouldin: 1.2905,
    calinskiHarabasz: 2750.8,
    stabilityAri: 0.915,
    runtimeMs: 65.3,
    noisePoints: 0,
    description: 'Expectation-Maximization with full covariance structures for soft cluster membership.',
  },
];

export const mockPersonas: ClusterPersona[] = [
  {
    clusterId: 0,
    name: 'Transactors / Active Spenders',
    tagline: 'High purchase frequency, low revolving balance, zero cash advance',
    size: 2792,
    percentage: 31.2,
    color: '#10b981', // Emerald
    silhouetteScore: 0.621,
    description: 'Financially prudent customers who actively use credit for daily transactions and pay balances in full. Highly responsive to cashback and retail rewards.',
    radarMetrics: [
      { feature: 'Balance', value: 0.22, rawValue: 680.50 },
      { feature: 'Purchases', value: 0.78, rawValue: 2450.00 },
      { feature: 'Cash Advance', value: 0.05, rawValue: 45.00 },
      { feature: 'Credit Limit', value: 0.65, rawValue: 6200.00 },
      { feature: 'Payments', value: 0.72, rawValue: 2310.00 },
      { feature: 'Full Payment %', value: 0.85, rawValue: 0.85 },
    ],
    keyAttributes: [
      { label: 'Avg Balance', value: '$680.50' },
      { label: 'Avg Purchases', value: '$2,450.00' },
      { label: 'Payment Ratio', value: '85.0%' },
      { label: 'Risk Tier', value: 'Ultra-Low Risk' },
    ],
    recommendations: [
      'Offer 2-3% tiered merchant cashback programs to increase interchange revenue.',
      'Target with premium travel card upgrade promotions.',
      'Maintain auto-payment convenience features.',
    ],
  },
  {
    clusterId: 1,
    name: 'Cash Advance Borrowers',
    tagline: 'High liquidity seeking, frequent ATM cash advances, minimum payments',
    size: 2193,
    percentage: 24.5,
    color: '#f59e0b', // Amber
    silhouetteScore: 0.548,
    description: 'Customers primarily using the credit card as a short-term liquidity bridge. High cash advance transactions, high interest charges, lower direct retail purchases.',
    radarMetrics: [
      { feature: 'Balance', value: 0.74, rawValue: 3890.00 },
      { feature: 'Purchases', value: 0.12, rawValue: 180.00 },
      { feature: 'Cash Advance', value: 0.89, rawValue: 3450.00 },
      { feature: 'Credit Limit', value: 0.48, rawValue: 4500.00 },
      { feature: 'Payments', value: 0.42, rawValue: 1120.00 },
      { feature: 'Full Payment %', value: 0.08, rawValue: 0.08 },
    ],
    keyAttributes: [
      { label: 'Avg Balance', value: '$3,890.00' },
      { label: 'Avg Cash Adv', value: '$3,450.00' },
      { label: 'Cash Adv Freq', value: '0.48 (High)' },
      { label: 'Risk Tier', value: 'Moderate-High Risk' },
    ],
    recommendations: [
      'Promote lower-APR balance transfer offers to consolidate high-interest debt.',
      'Implement real-time liquidity warnings when approaching credit limits.',
      'Structure installment payoff plans with fixed repayment schedules.',
    ],
  },
  {
    clusterId: 2,
    name: 'High Spenders / VIP Elite',
    tagline: 'Massive credit limits, large one-off purchases, substantial payments',
    size: 1683,
    percentage: 18.8,
    color: '#8b5cf6', // Violet
    silhouetteScore: 0.654,
    description: 'High net worth or affluent cardholders generating high transaction volume, substantial one-off purchases, and maintaining large credit limits with dependable payments.',
    radarMetrics: [
      { feature: 'Balance', value: 0.88, rawValue: 4950.00 },
      { feature: 'Purchases', value: 0.95, rawValue: 4820.00 },
      { feature: 'Cash Advance', value: 0.28, rawValue: 850.00 },
      { feature: 'Credit Limit', value: 0.92, rawValue: 11500.00 },
      { feature: 'Payments', value: 0.94, rawValue: 4650.00 },
      { feature: 'Full Payment %', value: 0.52, rawValue: 0.52 },
    ],
    keyAttributes: [
      { label: 'Avg Balance', value: '$4,950.00' },
      { label: 'Avg Purchases', value: '$4,820.00' },
      { label: 'Avg Credit Limit', value: '$11,500.00' },
      { label: 'Risk Tier', value: 'High Value / Low Risk' },
    ],
    recommendations: [
      'Assign dedicated relationship manager and exclusive concierge perks.',
      'Offer luxury retail and airline co-branded point multipliers.',
      'Provide proactive credit line increases up to $25k+.',
    ],
  },
  {
    clusterId: 3,
    name: 'Low-Engagement / Inactive',
    tagline: 'Low balance, near-zero transactions, minimal card utilization',
    size: 2282,
    percentage: 25.5,
    color: '#06b6d4', // Cyan
    silhouetteScore: 0.512,
    description: 'Dormant or budget-conscious accounts with minimal balance, low credit limits, and rare purchase activity. High risk of churn or account dormancy.',
    radarMetrics: [
      { feature: 'Balance', value: 0.15, rawValue: 240.00 },
      { feature: 'Purchases', value: 0.08, rawValue: 75.00 },
      { feature: 'Cash Advance', value: 0.06, rawValue: 50.00 },
      { feature: 'Credit Limit', value: 0.22, rawValue: 1800.00 },
      { feature: 'Payments', value: 0.18, rawValue: 290.00 },
      { feature: 'Full Payment %', value: 0.25, rawValue: 0.25 },
    ],
    keyAttributes: [
      { label: 'Avg Balance', value: '$240.00' },
      { label: 'Avg Purchases', value: '$75.00' },
      { label: 'Utilization', value: '13.3%' },
      { label: 'Risk Tier', value: 'Dormancy / Churn Risk' },
    ],
    recommendations: [
      'Deploy re-engagement marketing campaigns with statement credits ($25 for 3 transactions).',
      'Waive annual fees upon reactivation to prevent account closure.',
      'Survey customers to identify barriers to primary card status.',
    ],
  },
];

// Generate 400 deterministic projection points for 2D/3D visualizations
export const mockPoints2D: ClusterPoint2D[] = Array.from({ length: 400 }, (_, i) => {
  const cluster = i % 4;
  const id = `CUST_${(10001 + i).toString()}`;
  let cx = 0, cy = 0, baseBalance = 0, basePurchases = 0, baseLimit = 0, baseCashAdv = 0;

  if (cluster === 0) { // Transactors
    cx = 2.8 + (Math.sin(i * 1.7) * 0.9);
    cy = 1.6 + (Math.cos(i * 1.3) * 0.85);
    baseBalance = 500 + (i % 30) * 30;
    basePurchases = 1800 + (i % 40) * 50;
    baseLimit = 5000 + (i % 25) * 150;
    baseCashAdv = 0 + (i % 5) * 10;
  } else if (cluster === 1) { // Cash Advance
    cx = -2.4 + (Math.cos(i * 2.1) * 0.95);
    cy = 2.5 + (Math.sin(i * 1.4) * 0.8);
    baseBalance = 3200 + (i % 30) * 60;
    basePurchases = 100 + (i % 20) * 15;
    baseLimit = 4000 + (i % 20) * 100;
    baseCashAdv = 2800 + (i % 30) * 80;
  } else if (cluster === 2) { // VIP Elite
    cx = 0.5 + (Math.sin(i * 1.9) * 0.9);
    cy = -2.7 + (Math.cos(i * 2.3) * 0.75);
    baseBalance = 4500 + (i % 25) * 80;
    basePurchases = 4200 + (i % 35) * 90;
    baseLimit = 10000 + (i % 30) * 200;
    baseCashAdv = 600 + (i % 20) * 30;
  } else { // Inactive
    cx = -1.8 + (Math.cos(i * 1.5) * 0.85);
    cy = -1.4 + (Math.sin(i * 2.5) * 0.8);
    baseBalance = 200 + (i % 15) * 15;
    basePurchases = 60 + (i % 10) * 10;
    baseLimit = 1500 + (i % 15) * 50;
    baseCashAdv = 40 + (i % 8) * 10;
  }

  return {
    id,
    x: Number(cx.toFixed(3)),
    y: Number(cy.toFixed(3)),
    cluster,
    balance: baseBalance,
    purchases: basePurchases,
    creditLimit: baseLimit,
    cashAdvance: baseCashAdv,
    payments: Math.round(basePurchases * 0.85 + baseBalance * 0.1),
  };
});

export const mockPoints3D: ClusterPoint3D[] = mockPoints2D.map((p, idx) => {
  let cz = 0;
  if (p.cluster === 0) cz = 1.4 + Math.sin(idx * 1.1) * 0.8;
  else if (p.cluster === 1) cz = -2.1 + Math.cos(idx * 1.3) * 0.7;
  else if (p.cluster === 2) cz = 2.8 + Math.sin(idx * 1.5) * 0.9;
  else cz = -1.2 + Math.cos(idx * 0.9) * 0.6;

  return {
    ...p,
    z: Number(cz.toFixed(3)),
  };
});

export const mockSilhouetteSamples: SilhouetteSample[] = Array.from({ length: 240 }, (_, idx) => {
  const cluster = Math.floor(idx / 60);
  const sampleInCluster = idx % 60;
  let score = 0;
  if (cluster === 0) score = 0.78 - (sampleInCluster / 60) * 0.35 + (Math.sin(idx) * 0.04);
  else if (cluster === 1) score = 0.70 - (sampleInCluster / 60) * 0.42 + (Math.cos(idx) * 0.05);
  else if (cluster === 2) score = 0.82 - (sampleInCluster / 60) * 0.32 + (Math.sin(idx * 2) * 0.03);
  else score = 0.65 - (sampleInCluster / 60) * 0.45 + (Math.cos(idx * 1.5) * 0.04);

  return {
    cluster,
    score: Number(Math.max(-0.05, Math.min(0.95, score)).toFixed(3)),
    sampleIndex: idx,
  };
});

export const mockElbowPoints: ElbowPoint[] = [
  { k: 2, inertia: 18450.2, isElbow: false },
  { k: 3, inertia: 12200.8, isElbow: false },
  { k: 4, inertia: 7850.4, isElbow: true }, // Kneedle Knee Point
  { k: 5, inertia: 6420.1, isElbow: false },
  { k: 6, inertia: 5410.7, isElbow: false },
  { k: 7, inertia: 4680.3, isElbow: false },
  { k: 8, inertia: 4120.9, isElbow: false },
  { k: 9, inertia: 3710.5, isElbow: false },
  { k: 10, inertia: 3390.2, isElbow: false },
];

export const mockAutoresearchHistory: AutoresearchStep[] = [
  {
    step: 1,
    timestamp: '2026-08-28T08:00:10Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'random', max_iter: 300 },
    preprocessing: { scaler: 'StandardScaler', imputation: 'mean' },
    silhouetteScore: 0.442,
    daviesBouldinIndex: 1.341,
    calinskiHarabaszIndex: 2842,
    stabilityScore: 0.92,
    compositeFitness: 0.512,
    status: 'ACCEPTED',
    mutationDescription: 'Baseline initial initialization (StandardScaler + K-Means k=4)',
    deltaSilhouette: 0.0,
    temperature: 1.0,
  },
  {
    step: 2,
    timestamp: '2026-08-28T08:00:14Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 10 },
    preprocessing: { scaler: 'StandardScaler', imputation: 'median' },
    silhouetteScore: 0.458,
    daviesBouldinIndex: 1.298,
    calinskiHarabaszIndex: 2910,
    stabilityScore: 0.94,
    compositeFitness: 0.534,
    status: 'ACCEPTED',
    mutationDescription: 'Switched init: random -> k-means++, Imputation: mean -> median',
    deltaSilhouette: 0.016,
    temperature: 0.96,
  },
  {
    step: 3,
    timestamp: '2026-08-28T08:00:18Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 5, init: 'k-means++', n_init: 10 },
    preprocessing: { scaler: 'StandardScaler', imputation: 'median' },
    silhouetteScore: 0.432,
    daviesBouldinIndex: 1.380,
    calinskiHarabaszIndex: 2750,
    stabilityScore: 0.91,
    compositeFitness: 0.498,
    status: 'REJECTED',
    mutationDescription: 'Mutated k: 4 -> 5 (Score degraded, rejected)',
    deltaSilhouette: -0.026,
    temperature: 0.92,
  },
  {
    step: 4,
    timestamp: '2026-08-28T08:00:23Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 15 },
    preprocessing: { scaler: 'RobustScaler', imputation: 'median' },
    silhouetteScore: 0.482,
    daviesBouldinIndex: 1.185,
    calinskiHarabaszIndex: 3120,
    stabilityScore: 0.95,
    compositeFitness: 0.568,
    status: 'ACCEPTED',
    mutationDescription: 'Mutated Scaler: StandardScaler -> RobustScaler (IQR normalization)',
    deltaSilhouette: 0.024,
    temperature: 0.88,
  },
  {
    step: 5,
    timestamp: '2026-08-28T08:00:28Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 20 },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', imputation: 'median' },
    silhouetteScore: 0.524,
    daviesBouldinIndex: 1.042,
    calinskiHarabaszIndex: 3410,
    stabilityScore: 0.96,
    compositeFitness: 0.625,
    status: 'ACCEPTED',
    mutationDescription: 'Applied Yeo-Johnson power transform to stabilize heavy skewness',
    deltaSilhouette: 0.042,
    temperature: 0.84,
  },
  {
    step: 6,
    timestamp: '2026-08-28T08:00:33Z',
    algorithm: 'DBSCAN',
    hyperparameters: { eps: 0.45, min_samples: 5 },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', imputation: 'median' },
    silhouetteScore: 0.395,
    daviesBouldinIndex: 1.540,
    calinskiHarabaszIndex: 1680,
    stabilityScore: 0.82,
    compositeFitness: 0.440,
    status: 'REJECTED',
    mutationDescription: 'Explored Density paradigm DBSCAN (eps=0.45, noise ratio high 18%)',
    deltaSilhouette: -0.129,
    temperature: 0.80,
  },
  {
    step: 7,
    timestamp: '2026-08-28T08:00:38Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 20 },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', dim_red: 'PCA (n=12)' },
    silhouetteScore: 0.551,
    daviesBouldinIndex: 0.945,
    calinskiHarabaszIndex: 3620,
    stabilityScore: 0.97,
    compositeFitness: 0.672,
    status: 'ACCEPTED',
    mutationDescription: 'Added PCA feature denoising retaining 95% cumulative variance',
    deltaSilhouette: 0.027,
    temperature: 0.76,
  },
  {
    step: 8,
    timestamp: '2026-08-28T08:00:44Z',
    algorithm: 'Agglomerative',
    hyperparameters: { k: 4, linkage: 'ward' },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', dim_red: 'PCA (n=12)' },
    silhouetteScore: 0.538,
    daviesBouldinIndex: 0.985,
    calinskiHarabaszIndex: 3490,
    stabilityScore: 0.95,
    compositeFitness: 0.648,
    status: 'REJECTED',
    mutationDescription: 'Tested Hierarchical Ward linkage (Slightly sub-optimal to K-Means)',
    deltaSilhouette: -0.013,
    temperature: 0.72,
  },
  {
    step: 9,
    timestamp: '2026-08-28T08:00:50Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 25, algorithm: 'elkan' },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', dim_red: 'PCA (n=12)', winsorize: '1%-99%' },
    silhouetteScore: 0.584,
    daviesBouldinIndex: 0.812,
    calinskiHarabaszIndex: 3921,
    stabilityScore: 0.98,
    compositeFitness: 0.738,
    status: 'ACCEPTED',
    mutationDescription: 'Added 1%-99% Winsorization outlier clipping + Elkan triangle inequality',
    deltaSilhouette: 0.033,
    temperature: 0.68,
  },
  {
    step: 10,
    timestamp: '2026-08-28T08:00:56Z',
    algorithm: 'K-Means',
    hyperparameters: { k: 4, init: 'k-means++', n_init: 30 },
    preprocessing: { scaler: 'PowerTransformer (Yeo-Johnson)', dim_red: 'PCA (n=10)', winsorize: '1%-99%' },
    silhouetteScore: 0.578,
    daviesBouldinIndex: 0.835,
    calinskiHarabaszIndex: 3870,
    stabilityScore: 0.97,
    compositeFitness: 0.725,
    status: 'REJECTED',
    mutationDescription: 'Reduced PCA components 12 -> 10 (Slight loss of variance)',
    deltaSilhouette: -0.006,
    temperature: 0.64,
  },
];

export const mockLeaderboard: AutoresearchLeaderboardItem[] = [
  {
    rank: 1,
    trialId: 28,
    algorithm: 'K-Means++ (Elkan)',
    preprocessing: 'Yeo-Johnson + Winsorization + PCA(12)',
    hyperparameters: 'k=4, n_init=25, tol=1e-4',
    silhouette: 0.5842,
    daviesBouldin: 0.8124,
    calinskiHarabasz: 3921.6,
    stability: 0.982,
    compositeFitness: 0.7384,
    runtimeMs: 24.2,
    isPareto: true,
  },
  {
    rank: 2,
    trialId: 19,
    algorithm: 'GMM (Full Covariance)',
    preprocessing: 'Yeo-Johnson + RobustScaler + PCA(14)',
    hyperparameters: 'k=4, reg_covar=1e-5, n_init=5',
    silhouette: 0.5621,
    daviesBouldin: 0.8950,
    calinskiHarabasz: 3640.5,
    stability: 0.965,
    compositeFitness: 0.7012,
    runtimeMs: 78.1,
    isPareto: true,
  },
  {
    rank: 3,
    trialId: 12,
    algorithm: 'Agglomerative (Ward)',
    preprocessing: 'Yeo-Johnson + PCA(12)',
    hyperparameters: 'k=4, metric=euclidean',
    silhouette: 0.5490,
    daviesBouldin: 0.9210,
    calinskiHarabasz: 3510.2,
    stability: 0.958,
    compositeFitness: 0.6780,
    runtimeMs: 145.0,
    isPareto: false,
  },
  {
    rank: 4,
    trialId: 22,
    algorithm: 'HDBSCAN',
    preprocessing: 'Yeo-Johnson + UMAP(2D)',
    hyperparameters: 'min_cluster=45, min_samples=8',
    silhouette: 0.5284,
    daviesBouldin: 0.9820,
    calinskiHarabasz: 3340.1,
    stability: 0.942,
    compositeFitness: 0.6450,
    runtimeMs: 88.6,
    isPareto: false,
  },
  {
    rank: 5,
    trialId: 7,
    algorithm: 'K-Means++',
    preprocessing: 'RobustScaler + Median Impute',
    hyperparameters: 'k=4, n_init=15',
    silhouette: 0.4821,
    daviesBouldin: 1.1850,
    calinskiHarabasz: 3120.0,
    stability: 0.948,
    compositeFitness: 0.5680,
    runtimeMs: 19.5,
    isPareto: false,
  },
  {
    rank: 6,
    trialId: 1,
    algorithm: 'K-Means (Baseline)',
    preprocessing: 'StandardScaler + Mean Impute',
    hyperparameters: 'k=4, n_init=10, init=random',
    silhouette: 0.4421,
    daviesBouldin: 1.3412,
    calinskiHarabasz: 2842.1,
    stability: 0.921,
    compositeFitness: 0.5120,
    runtimeMs: 18.4,
    isPareto: false,
  },
];

export const mockBenchmarkRows: BenchmarkRow[] = [
  {
    algorithm: 'K-Means (Baseline)',
    paradigm: 'Partitioning',
    isOptimized: false,
    kOrEps: 'k=4, raw features',
    silhouetteMean: 0.442,
    silhouetteStd: 0.012,
    daviesBouldinMean: 1.341,
    daviesBouldinStd: 0.034,
    calinskiHarabaszMean: 2842.1,
    calinskiHarabaszStd: 45.2,
    stabilityScore: 0.921,
    runtimeMs: 18.4,
    outlierRatio: 0.0,
  },
  {
    algorithm: 'K-Means (Hill-Climbed)',
    paradigm: 'Partitioning',
    isOptimized: true,
    kOrEps: 'k=4, Yeo-Johnson+PCA',
    silhouetteMean: 0.584,
    silhouetteStd: 0.009,
    daviesBouldinMean: 0.812,
    daviesBouldinStd: 0.021,
    calinskiHarabaszMean: 3921.6,
    calinskiHarabaszStd: 38.4,
    stabilityScore: 0.982,
    runtimeMs: 24.2,
    outlierRatio: 0.0,
  },
  {
    algorithm: 'K-Medoids (FasterPAM)',
    paradigm: 'Partitioning',
    isOptimized: false,
    kOrEps: 'k=4, Manhattan',
    silhouetteMean: 0.428,
    silhouetteStd: 0.015,
    daviesBouldinMean: 1.410,
    daviesBouldinStd: 0.041,
    calinskiHarabaszMean: 2650.4,
    calinskiHarabaszStd: 52.1,
    stabilityScore: 0.894,
    runtimeMs: 112.5,
    outlierRatio: 0.0,
  },
  {
    algorithm: 'DBSCAN (Baseline)',
    paradigm: 'Density',
    isOptimized: false,
    kOrEps: 'eps=0.5, min_samp=5',
    silhouetteMean: 0.381,
    silhouetteStd: 0.025,
    daviesBouldinMean: 1.624,
    daviesBouldinStd: 0.052,
    calinskiHarabaszMean: 1412.0,
    calinskiHarabaszStd: 82.1,
    stabilityScore: 0.812,
    runtimeMs: 42.1,
    outlierRatio: 0.142,
  },
  {
    algorithm: 'HDBSCAN (Hierarchical)',
    paradigm: 'Density',
    isOptimized: false,
    kOrEps: 'min_cluster=50',
    silhouetteMean: 0.495,
    silhouetteStd: 0.015,
    daviesBouldinMean: 1.052,
    daviesBouldinStd: 0.028,
    calinskiHarabaszMean: 3105.4,
    calinskiHarabaszStd: 51.0,
    stabilityScore: 0.941,
    runtimeMs: 88.6,
    outlierRatio: 0.051,
  },
  {
    algorithm: 'Agglomerative (Ward)',
    paradigm: 'Hierarchical',
    isOptimized: false,
    kOrEps: 'k=4, Ward linkage',
    silhouetteMean: 0.468,
    silhouetteStd: 0.011,
    daviesBouldinMean: 1.215,
    daviesBouldinStd: 0.030,
    calinskiHarabaszMean: 2980.2,
    calinskiHarabaszStd: 41.2,
    stabilityScore: 0.948,
    runtimeMs: 145.0,
    outlierRatio: 0.0,
  },
  {
    algorithm: 'GMM (Full Covariance)',
    paradigm: 'Probabilistic',
    isOptimized: false,
    kOrEps: 'k=4, full covar',
    silhouetteMean: 0.451,
    silhouetteStd: 0.018,
    daviesBouldinMean: 1.290,
    daviesBouldinStd: 0.040,
    calinskiHarabaszMean: 2750.8,
    calinskiHarabaszStd: 60.1,
    stabilityScore: 0.915,
    runtimeMs: 65.3,
    outlierRatio: 0.0,
  },
  {
    algorithm: 'GMM (Hill-Climbed)',
    paradigm: 'Probabilistic',
    isOptimized: true,
    kOrEps: 'k=4, Yeo-Johnson+PCA',
    silhouetteMean: 0.562,
    silhouetteStd: 0.010,
    daviesBouldinMean: 0.895,
    daviesBouldinStd: 0.025,
    calinskiHarabaszMean: 3640.5,
    calinskiHarabaszStd: 44.0,
    stabilityScore: 0.965,
    runtimeMs: 78.1,
    outlierRatio: 0.0,
  },
];

export const mockAblationEntries: AblationEntry[] = [
  {
    stage: '1. Raw Baseline',
    component: 'StandardScaler + K-Means (Random Init)',
    description: 'Raw feature space with Euclidean distances, vulnerable to skew and extreme outliers.',
    silhouette: 0.382,
    deltaSilhouette: 0.0,
    daviesBouldin: 1.482,
    calinskiHarabasz: 2410.0,
    stability: 0.88,
  },
  {
    stage: '2. Robust Cleaning',
    component: '+ Median Impute & Winsorization Capping',
    description: 'Replaced missing values and trimmed 99th percentile extreme credit limits.',
    silhouette: 0.442,
    deltaSilhouette: 0.060,
    daviesBouldin: 1.341,
    calinskiHarabasz: 2842.1,
    stability: 0.92,
  },
  {
    stage: '3. Variance Stabilization',
    component: '+ Yeo-Johnson Power Transformation',
    description: 'Monotonically compressed long-tailed monetary features into bell-shaped distributions.',
    silhouette: 0.524,
    deltaSilhouette: 0.082,
    daviesBouldin: 1.042,
    calinskiHarabasz: 3410.0,
    stability: 0.96,
  },
  {
    stage: '4. Dimensionality Denoising',
    component: '+ PCA 12 Components (95% Variance)',
    description: 'Eliminated collinear noise between one-off purchases and total transactions.',
    silhouette: 0.551,
    deltaSilhouette: 0.027,
    daviesBouldin: 0.945,
    calinskiHarabasz: 3620.0,
    stability: 0.97,
  },
  {
    stage: '5. Autoresearch Search Loop',
    component: '+ Hill-Climbing Hyperparameter Tuning',
    description: 'Optimized k-means++ seeding parameters, convergence tolerances, and distance metrics.',
    silhouette: 0.584,
    deltaSilhouette: 0.033,
    daviesBouldin: 0.812,
    calinskiHarabasz: 3921.6,
    stability: 0.98,
  },
];

export const mockLiteraturePapers: LiteraturePaper[] = [
  {
    id: 'rousseeuw1987',
    title: 'Silhouettes: A graphical aid to the interpretation and validation of cluster analysis',
    authors: 'Peter J. Rousseeuw',
    year: 1987,
    venue: 'Journal of Computational and Applied Mathematics, 20, 53-65',
    keyContribution: 'Formulated the Silhouette coefficient s(i) measuring within-cluster tightness versus nearest-cluster separation.',
    relevanceToProject: 'Serves as our primary internal clustering validation metric and primary fitness objective in autoresearch.',
    bibtex: `@article{rousseeuw1987silhouettes,
  title={Silhouettes: a graphical aid to the interpretation and validation of cluster analysis},
  author={Rousseeuw, Peter J},
  journal={Journal of Computational and Applied Mathematics},
  volume={20},
  pages={53--65},
  year={1987},
  publisher={Elsevier}
}`,
  },
  {
    id: 'daviesbouldin1979',
    title: 'A Cluster Separation Measure',
    authors: 'David L. Davies and Donald W. Bouldin',
    year: 1979,
    venue: 'IEEE Transactions on Pattern Analysis and Machine Intelligence, 1(2), 224-227',
    keyContribution: 'Introduced the Davies-Bouldin Index (DB) assessing average similarity between each cluster and its most similar counterpart.',
    relevanceToProject: 'Used as the primary minimization objective to ensure maximum inter-cluster dispersion.',
    bibtex: `@article{davies1979cluster,
  title={A cluster separation measure},
  author={Davies, David L and Bouldin, Donald W},
  journal={IEEE Transactions on Pattern Analysis and Machine Intelligence},
  volume={1},
  number={2},
  pages={224--227},
  year={1979},
  publisher={IEEE}
}`,
  },
  {
    id: 'calinskiharabasz1974',
    title: 'A dendrite method for cluster analysis',
    authors: 'Tadeusz Caliński and Jerzy Harabasz',
    year: 1974,
    venue: 'Communications in Statistics - Theory and Methods, 3(1), 1-27',
    keyContribution: 'Proposed the Variance Ratio Criterion (Calinski-Harabasz index) evaluating between-group to within-group variance.',
    relevanceToProject: 'Complementary evaluation metric verifying global geometric separation across high-density clusters.',
    bibtex: `@article{calinski1974dendrite,
  title={A dendrite method for cluster analysis},
  author={Cali{\\'n}ski, Tadeusz and Harabasz, Jerzy},
  journal={Communications in Statistics-theory and Methods},
  volume={3},
  number={1},
  pages={1--27},
  year={1974},
  publisher={Taylor \\& Francis}
}`,
  },
  {
    id: 'arthur2007',
    title: 'k-means++: The advantages of careful seeding',
    authors: 'David Arthur and Sergei Vassilvitskii',
    year: 2007,
    venue: 'Proceedings of the Eighteenth Annual ACM-SIAM Symposium on Discrete Algorithms (SODA)',
    keyContribution: 'Proved an O(log k) approximation guarantee for K-Means using randomized proportional distance initialization.',
    relevanceToProject: 'Standard initialization algorithm implemented across our baseline and hill-climbed partitioning pipelines.',
    bibtex: `@inproceedings{arthur2007k,
  title={k-means++: The advantages of careful seeding},
  author={Arthur, David and Vassilvitskii, Sergei},
  booktitle={Proceedings of the eighteenth annual ACM-SIAM symposium on Discrete algorithms},
  pages={1027--1035},
  year={2007}
}`,
  },
  {
    id: 'campello2013',
    title: 'Density-Based Clustering Based on Hierarchical Density Estimates',
    authors: 'Ricardo J. G. B. Campello, Davoud Moulavi, and Jörg Sander',
    year: 2013,
    venue: 'Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD)',
    keyContribution: 'Introduced HDBSCAN, combining hierarchical clustering with DBSCAN to discover clusters of variable density.',
    relevanceToProject: 'Employed in Milestone 1 and Milestone 4 as the premier density-based model robust to non-uniform financial data densities.',
    bibtex: `@inproceedings{campello2013density,
  title={Density-based clustering based on hierarchical density estimates},
  author={Campello, Ricardo JGB and Moulavi, Davoud and Sander, J{\\"o}rg},
  booktitle={Pacific-Asia conference on knowledge discovery and data mining},
  pages={160--172},
  year={2013},
  organization={Springer}
}`,
  },
  {
    id: 'mcinnes2018',
    title: 'UMAP: Uniform Manifold Approximation and Projection for Dimension Reduction',
    authors: 'Leland McInnes, John Healy, and James Melville',
    year: 2018,
    venue: 'arXiv preprint arXiv:1802.03426',
    keyContribution: 'Theoretical foundation for non-linear manifold learning preserving local and global topological structure.',
    relevanceToProject: 'Used alongside PCA for high-fidelity 2D non-linear customer manifold projections in the Cluster Explorer.',
    bibtex: `@article{mcinnes2018umap,
  title={UMAP: Uniform manifold approximation and projection for dimension reduction},
  author={McInnes, Leland and Healy, John and Melville, James},
  journal={arXiv preprint arXiv:1802.03426},
  year={2018}
}`,
  },
];

export const mockCustomerPresets: Record<string, CustomerVector> = {
  vip: {
    balance: 5200.0,
    balanceFrequency: 1.0,
    purchases: 4850.0,
    oneOffPurchases: 3200.0,
    installmentsPurchases: 1650.0,
    cashAdvance: 0.0,
    purchasesFrequency: 0.95,
    oneOffPurchasesFrequency: 0.85,
    purchasesInstallmentsFrequency: 0.75,
    cashAdvanceFrequency: 0.0,
    cashAdvanceTrx: 0,
    purchasesTrx: 48,
    creditLimit: 12000.0,
    payments: 4600.0,
    minimumPayments: 650.0,
    prcFullPayment: 0.85,
    tenure: 12,
  },
  revolver: {
    balance: 4100.0,
    balanceFrequency: 1.0,
    purchases: 150.0,
    oneOffPurchases: 50.0,
    installmentsPurchases: 100.0,
    cashAdvance: 3800.0,
    purchasesFrequency: 0.15,
    oneOffPurchasesFrequency: 0.05,
    purchasesInstallmentsFrequency: 0.10,
    cashAdvanceFrequency: 0.55,
    cashAdvanceTrx: 18,
    purchasesTrx: 3,
    creditLimit: 5000.0,
    payments: 1200.0,
    minimumPayments: 1100.0,
    prcFullPayment: 0.05,
    tenure: 12,
  },
  transactor: {
    balance: 650.0,
    balanceFrequency: 0.90,
    purchases: 2600.0,
    oneOffPurchases: 1800.0,
    installmentsPurchases: 800.0,
    cashAdvance: 0.0,
    purchasesFrequency: 0.92,
    oneOffPurchasesFrequency: 0.75,
    purchasesInstallmentsFrequency: 0.60,
    cashAdvanceFrequency: 0.0,
    cashAdvanceTrx: 0,
    purchasesTrx: 35,
    creditLimit: 6500.0,
    payments: 2450.0,
    minimumPayments: 210.0,
    prcFullPayment: 0.95,
    tenure: 12,
  },
  cashSeeker: {
    balance: 3100.0,
    balanceFrequency: 0.95,
    purchases: 80.0,
    oneOffPurchases: 0.0,
    installmentsPurchases: 80.0,
    cashAdvance: 2800.0,
    purchasesFrequency: 0.10,
    oneOffPurchasesFrequency: 0.0,
    purchasesInstallmentsFrequency: 0.10,
    cashAdvanceFrequency: 0.45,
    cashAdvanceTrx: 12,
    purchasesTrx: 2,
    creditLimit: 4000.0,
    payments: 950.0,
    minimumPayments: 850.0,
    prcFullPayment: 0.0,
    tenure: 12,
  },
  inactive: {
    balance: 180.0,
    balanceFrequency: 0.35,
    purchases: 45.0,
    oneOffPurchases: 0.0,
    installmentsPurchases: 45.0,
    cashAdvance: 0.0,
    purchasesFrequency: 0.10,
    oneOffPurchasesFrequency: 0.0,
    purchasesInstallmentsFrequency: 0.10,
    cashAdvanceFrequency: 0.0,
    cashAdvanceTrx: 0,
    purchasesTrx: 1,
    creditLimit: 1500.0,
    payments: 180.0,
    minimumPayments: 120.0,
    prcFullPayment: 0.50,
    tenure: 12,
  },
};

/**
 * Client-Side Real-Time Customer Profiler & Soft Inference Engine
 */
export function simulateCustomerInference(input: CustomerVector): InferenceResponse {
  // Normalize input features relative to population scales
  const normBalance = Math.min(1.0, input.balance / 6000.0);
  const normPurchases = Math.min(1.0, input.purchases / 5000.0);
  const normCashAdvance = Math.min(1.0, input.cashAdvance / 4000.0);
  const normCreditLimit = Math.min(1.0, input.creditLimit / 12000.0);
  const normPayments = Math.min(1.0, input.payments / 5000.0);
  const normFullPay = Math.min(1.0, input.prcFullPayment);

  // Cluster centroids in normalized 6D space
  const centroids = [
    { id: 0, v: [0.22, 0.78, 0.05, 0.65, 0.72, 0.85] }, // Transactor
    { id: 1, v: [0.74, 0.12, 0.89, 0.48, 0.42, 0.08] }, // Cash Advance
    { id: 2, v: [0.88, 0.95, 0.28, 0.92, 0.94, 0.52] }, // VIP Elite
    { id: 3, v: [0.15, 0.08, 0.06, 0.22, 0.18, 0.25] }, // Inactive
  ];

  const sample = [normBalance, normPurchases, normCashAdvance, normCreditLimit, normPayments, normFullPay];

  // Calculate Euclidean distances
  const distances = centroids.map((c) => {
    let sumSq = 0;
    for (let i = 0; i < sample.length; i++) {
      sumSq += Math.pow(sample[i] - c.v[i], 2);
    }
    return { id: c.id, dist: Math.sqrt(sumSq) };
  });

  // Softmax over negative distances with temperature T=0.45
  const temperature = 0.45;
  const expWeights = distances.map((d) => Math.exp(-d.dist / temperature));
  const sumExp = expWeights.reduce((a, b) => a + b, 0);
  const rawProbs = expWeights.map((w) => w / sumExp);

  // Find predicted cluster (min distance / max prob)
  let bestIdx = 0;
  let maxP = -1;
  rawProbs.forEach((p, idx) => {
    if (p > maxP) {
      maxP = p;
      bestIdx = idx;
    }
  });

  const predictedPersona = mockPersonas[bestIdx];

  const probabilities = mockPersonas.map((persona, idx) => ({
    clusterId: persona.clusterId,
    personaName: persona.name,
    probability: Number(rawProbs[idx].toFixed(4)),
    color: persona.color,
  }));

  const radarComparison = [
    { feature: 'Balance', sampleValue: Number(normBalance.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[0].value, populationMean: 0.35 },
    { feature: 'Purchases', sampleValue: Number(normPurchases.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[1].value, populationMean: 0.28 },
    { feature: 'Cash Advance', sampleValue: Number(normCashAdvance.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[2].value, populationMean: 0.20 },
    { feature: 'Credit Limit', sampleValue: Number(normCreditLimit.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[3].value, populationMean: 0.40 },
    { feature: 'Payments', sampleValue: Number(normPayments.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[4].value, populationMean: 0.32 },
    { feature: 'Full Payment %', sampleValue: Number(normFullPay.toFixed(2)), clusterCentroid: predictedPersona.radarMetrics[5].value, populationMean: 0.15 },
  ];

  const topContributingFeatures = [
    {
      feature: 'Purchases Volume',
      deviation: Number((normPurchases - 0.28).toFixed(2)),
      impact: normPurchases > 0.4 ? 'Positive' as const : normPurchases < 0.15 ? 'Negative' as const : 'Neutral' as const,
    },
    {
      feature: 'Cash Advance Usage',
      deviation: Number((normCashAdvance - 0.20).toFixed(2)),
      impact: normCashAdvance > 0.4 ? 'Positive' as const : 'Neutral' as const,
    },
    {
      feature: 'Credit Limit Utilization',
      deviation: Number((normCreditLimit - 0.40).toFixed(2)),
      impact: normCreditLimit > 0.6 ? 'Positive' as const : 'Neutral' as const,
    },
  ];

  return {
    predictedCluster: bestIdx,
    personaName: predictedPersona.name,
    tagline: predictedPersona.tagline,
    confidence: Number((maxP * 100).toFixed(1)),
    probabilities,
    radarComparison,
    topContributingFeatures,
    recommendations: predictedPersona.recommendations,
  };
}
